import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313",
        outline: "#909379",
        "secondary-container": "#474746",
        "inverse-primary": "#566500",
        "on-secondary-fixed-variant": "#474746",
        "on-primary-fixed": "#181e00",
        "surface-container": "#201f1f",
        secondary: "#c8c6c5",
        background: "#131313",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-error": "#690005",
        "primary-container": "#d1f107",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#636565",
        "tertiary-container": "#e2e2e2",
        "on-tertiary": "#2f3131",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-fixed-variant": "#404c00",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#e5e2e1",
        "surface-tint": "#b7d300",
        "outline-variant": "#454933",
        "secondary-fixed-dim": "#c8c6c5",
        error: "#ffb4ab",
        "on-primary": "#2c3400",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#d1f107",
        "surface-container-highest": "#353534",
        "on-secondary-fixed": "#1c1b1b",
        "on-surface-variant": "#c6c9ac",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        surface: "#131313",
        "on-primary-container": "#5c6b00",
        tertiary: "#ffffff",
        "on-background": "#e5e2e1",
        "on-secondary": "#313030",
        "on-secondary-container": "#b7b5b4",
        "primary-fixed-dim": "#b7d300",
        primary: "#ffffff",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed-dim": "#c6c6c7",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "text-muted": "#919191",
        "surface-elevated": "#222222",
        "surface-deep": "#141414",
        "chat-bubble-user": "#2F2F2F",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        base: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "stack-gap": "0.75rem",
        "margin-page": "2rem",
        "sidebar-width": "260px",
        "content-max-width": "800px",
      },
      maxWidth: {
        "container-max": "1280px",
        "content-max-width": "800px",
      },
      fontFamily: {
        "display-hero": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-hero": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": [
          "11px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "code-sm": ["13px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-hero-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "500" },
        ],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        fadeIn: "fadeIn 0.2s ease-out",
        slideUp: "slideUp 0.3s ease-out",
      },
    },
  },
  plugins: [],
} satisfies Config;
