ALTER TABLE users ADD COLUMN pin_hash TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN avatar_color TEXT DEFAULT '#d1f107';
ALTER TABLE users ADD COLUMN email TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN plan TEXT DEFAULT 'free';
ALTER TABLE users ADD COLUMN role TEXT DEFAULT 'developer';
