package agent

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/ozyassist/backend/internal/providers"
)

func TestPythonWorkspace_ExecutionAndFileCreation(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()

	pyCode := `
import os

print("Hello from Python Workspace!")
with open("test_generated_output.txt", "w", encoding="utf-8") as f:
    f.write("Generated by Python Workspace Engine")
`

	scriptName := "test_sample_script.py"
	output, ok := ExecutePythonInWorkspace(ctx, pyCode, scriptName, 15)
	if !ok {
		t.Fatalf("ejecución de Python falló: %s", output)
	}

	if !strings.Contains(output, "Hello from Python Workspace!") {
		t.Errorf("salida no contiene mensaje esperado: %s", output)
	}

	wsDir := GetWorkspaceDir()
	genFile := filepath.Join(wsDir, "test_generated_output.txt")
	defer os.Remove(genFile)
	defer os.Remove(filepath.Join(wsDir, scriptName))

	content, err := os.ReadFile(genFile)
	if err != nil {
		t.Fatalf("archivo generado no encontrado: %v", err)
	}

	if string(content) != "Generated by Python Workspace Engine" {
		t.Errorf("contenido inesperado: %s", string(content))
	}

	// Test os_workspace_list
	listOut, listOk := execOSWorkspaceList(ctx)
	if !listOk || !strings.Contains(strings.ToUpper(listOut), "MESA DE TRABAJO") {
		t.Errorf("execOSWorkspaceList falló: %s", listOut)
	}

	// Test execOSPythonExec ToolCall
	inputJSON := `{"code": "import math\nprint(f'PI={math.pi}')"}`
	tc := providers.ToolCall{
		ID:    "call_test_py",
		Name:  "os_python_exec",
		Input: []byte(inputJSON),
	}
	tcOut, tcOk := execOSPythonExec(ctx, tc)
	if !tcOk || !strings.Contains(tcOut, "PI=3.14159") {
		t.Errorf("execOSPythonExec falló: %s", tcOut)
	}
}

func TestPythonWorkspace_EmptyCode(t *testing.T) {
	ctx := context.Background()
	_, ok := ExecutePythonInWorkspace(ctx, "   ", "empty.py", 5)
	if ok {
		t.Errorf("esperaba fallo con código vacío")
	}
}
